name: AUTO_ADD_LABEL

on:
  pull_request:
  issue_comment:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dep
        run: yarn

      - name: Setup Demobox
        run: node scripts/github-robot/add-labels/index.js
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
